import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, unlinkSync, writeFileSync, renameSync } from 'node:fs';
import { dirname, extname, relative, resolve } from 'node:path';
import type { RefactorOperation } from './refactor-types.js';
import { assessRefactorSafety } from './refactor-safety.js';

const extensions = ['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.php']; const ignored = new Set(['node_modules', 'vendor', 'dist', 'build', '.git', '.ycf']);
function walk(directory: string): string[] { const out: string[] = []; for (const entry of readdirSync(directory)) { if (ignored.has(entry)) continue; const file = resolve(directory, entry); const info = statSync(file); if (info.isDirectory()) out.push(...walk(file)); else if (extensions.includes(extname(file))) out.push(file); } return out; }
function stripExt(file: string): string { return file.replace(/\.(?:[cm]?js|jsx|tsx?|php)$/i, ''); }
function sameModule(a: string, b: string): boolean { return stripExt(resolve(a)).toLowerCase() === stripExt(resolve(b)).toLowerCase(); }
function atomicWrite(file: string, content: string): void { const temp = `${file}.ycf-tmp-${process.pid}`; writeFileSync(temp, content, 'utf8'); renameSync(temp, file); }
function relativeSpecifier(importer: string, destination: string, original: string): string { const next = relative(dirname(importer), destination).replaceAll('\\', '/'); const value = next.startsWith('.') ? next : `./${next}`; return /\.(?:[cm]?js|jsx|tsx?|php)$/i.test(original) ? value : stripExt(value); }
interface Alias { pattern: string; targets: string[]; baseUrl: string; }
function aliases(root: string): Alias[] { for (const name of ['tsconfig.json', 'jsconfig.json']) { const file = resolve(root, name); if (!existsSync(file)) continue; try { const json = JSON.parse(readFileSync(file, 'utf8').replace(/\/\/.*$/gm, '').replace(/,\s*([}\]])/g, '$1')) as { compilerOptions?: { baseUrl?: string; paths?: Record<string, string[]> } }; const baseUrl = resolve(root, json.compilerOptions?.baseUrl ?? '.'); return Object.entries(json.compilerOptions?.paths ?? {}).map(([pattern, targets]) => ({ pattern, targets, baseUrl })); } catch { return []; } } return []; }
function resolveImport(importer: string, specifier: string, root: string, configured: Alias[]): string | undefined { const candidates: string[] = []; if (specifier.startsWith('.') || specifier.startsWith('/')) candidates.push(resolve(dirname(importer), specifier)); for (const alias of configured) { const escaped = alias.pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace('\\*', '(.*)'); const match = specifier.match(new RegExp(`^${escaped}$`)); if (match) for (const target of alias.targets) candidates.push(resolve(alias.baseUrl, target.replace('*', match[1] ?? ''))); } for (const base of candidates) for (const file of [base, ...extensions.map((extension) => `${base}${extension}`), ...extensions.map((extension) => resolve(base, `index${extension}`))]) if (existsSync(file)) return file; return undefined; }
function rewriteReferences(root: string, source: string, destination: string): { changed: string[]; before: Map<string, string> } { const sourceAbs = resolve(root, source); const destinationAbs = resolve(root, destination); const configured = aliases(root); const before = new Map<string, string>(); const changed: string[] = []; const pattern = /\b(?:from\s*|export\s+(?:type\s+)?[^;]*?\sfrom\s*|import\s*\(\s*|require\s*\(\s*)(["'])([^"']+)\1/g; for (const file of walk(root)) { const original = readFileSync(file, 'utf8'); const updated = original.replace(pattern, (whole, _quote: string, specifier: string) => { const resolved = resolveImport(file, specifier, root, configured); return resolved && sameModule(resolved, sourceAbs) ? whole.replace(specifier, relativeSpecifier(file, destinationAbs, specifier)) : whole; }); if (updated !== original) { before.set(file, original); atomicWrite(file, updated); changed.push(relative(root, file)); } } const moved = readFileSync(sourceAbs, 'utf8'); const internal = moved.replace(pattern, (whole, _quote: string, specifier: string) => { const resolved = resolveImport(sourceAbs, specifier, root, configured); if (!resolved) { if (specifier.startsWith('.')) throw new Error(`BLOCK: cannot resolve internal import ${specifier} in ${source}`); return whole; } return whole.replace(specifier, relativeSpecifier(destinationAbs, resolved, specifier)); }); if (internal !== moved) { before.set(sourceAbs, moved); atomicWrite(sourceAbs, internal); } return { changed, before }; }

export interface AppliedOperation { operationId: string; changedFiles: string[]; description: string; undo: () => void; }
export function applyRefactorOperation(target: string, operation: RefactorOperation): AppliedOperation { const root = resolve(target); const id = operation.id;
  if (operation.kind === 'MOVE' || operation.kind === 'RENAME') { const source = resolve(root, operation.source); const destination = resolve(root, operation.destination); if (!existsSync(source)) throw new Error(`Source does not exist: ${operation.source}`); if (existsSync(destination)) throw new Error(`Destination already exists: ${operation.destination}`); const contents = new Map(walk(root).map((file) => [file, readFileSync(file, 'utf8')])); const safety = assessRefactorSafety([source], contents); if (safety.mode === 'BLOCKED') throw new Error(`BLOCK: ${safety.reason}`); const ref = operation.updateImports ? rewriteReferences(root, operation.source, operation.destination) : { changed: [], before: new Map<string, string>() }; mkdirSync(dirname(destination), { recursive: true }); renameSync(source, destination); return { operationId: id, changedFiles: [...new Set([...ref.changed, operation.source, operation.destination])], description: operation.description, undo: () => { if (existsSync(destination)) renameSync(destination, source); for (const [file, content] of ref.before) atomicWrite(file, content); } }; }
  if (operation.kind === 'CREATE') { const file = resolve(root, operation.file); if (existsSync(file)) throw new Error(`Destination already exists: ${operation.file}`); mkdirSync(dirname(file), { recursive: true }); atomicWrite(file, operation.content); return { operationId: id, changedFiles: [operation.file], description: operation.description, undo: () => { if (existsSync(file)) unlinkSync(file); } }; }
  if (operation.kind === 'DELETE') { const file = resolve(root, operation.file); const content = readFileSync(file, 'utf8'); unlinkSync(file); return { operationId: id, changedFiles: [operation.file], description: operation.description, undo: () => { mkdirSync(dirname(file), { recursive: true }); atomicWrite(file, content); } }; }
  if (operation.kind === 'EDIT_IMPORT' || operation.kind === 'EDIT_EXPORT') { const file = resolve(root, operation.file); const before = readFileSync(file, 'utf8'); let after = before; for (const replacement of operation.replacements) after = after.split(replacement.from).join(replacement.to); if (after !== before) atomicWrite(file, after); return { operationId: id, changedFiles: after === before ? [] : [operation.file], description: operation.description, undo: () => atomicWrite(file, before) }; }
  if (operation.kind === 'EXTRACT') { const source = resolve(root, operation.sourceFile); const destination = resolve(root, operation.targetFile); if (existsSync(destination)) throw new Error(`Destination already exists: ${operation.targetFile}`); const before = readFileSync(source, 'utf8'); const lines = before.split(/\r?\n/); const selected = lines.slice(operation.range.startLine - 1, operation.range.endLine); if (!selected.length || /\bthis\b|\bsuper\b/.test(selected.join('\n'))) throw new Error('SUPERVISED: extraction has ambiguous outer scope.'); const extracted = selected.join('\n').replace(/^\s*(function|const|class|type|interface)\s+/m, 'export $1 '); mkdirSync(dirname(destination), { recursive: true }); atomicWrite(destination, `${extracted}\n`); const remaining = [...lines.slice(0, operation.range.startLine - 1), ...lines.slice(operation.range.endLine)].join('\n'); const path = relativeSpecifier(source, destination, './x'); atomicWrite(source, `import { ${operation.exportedNames.join(', ')} } from '${path}';\nexport { ${operation.exportedNames.join(', ')} };\n${remaining}`); return { operationId: id, changedFiles: [operation.sourceFile, operation.targetFile], description: operation.description, undo: () => { atomicWrite(source, before); if (existsSync(destination)) unlinkSync(destination); } }; }
  if (operation.kind === 'CONSOLIDATE') { const canonical = resolve(root, operation.canonicalFile); const duplicate = resolve(root, operation.duplicateFile); if (readFileSync(canonical, 'utf8').replace(/\s/g, '') !== readFileSync(duplicate, 'utf8').replace(/\s/g, '')) throw new Error('SUPERVISED: files are not exact duplicates.'); const ref = rewriteReferences(root, operation.duplicateFile, operation.canonicalFile); const duplicateContent = readFileSync(duplicate, 'utf8'); unlinkSync(duplicate); return { operationId: id, changedFiles: [...ref.changed, operation.duplicateFile], description: operation.description, undo: () => { atomicWrite(duplicate, duplicateContent); for (const [file, content] of ref.before) atomicWrite(file, content); } }; }
  throw new Error(`Unsupported operation: ${String(operation.kind)}`);
}
